<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Constants extends Model
{
    const STATUS_ENABLED = 'ENABLED';
    const STATUS_DISABLED = 'DISABLED';
    const STATUS_ACTIVE = 'ACTIVE';
    const STATUS_INACTIVE = 'INACTIVE';
    const STATUS_RESET = 'RESET PASSWORD';

    const DEFAULT_PAGINATOR = 25;

    const IMAGE_CATEGORY_PREFIX = 'Category_Image_';
    const IMAGE_SUB_CATEGORY_PREFIX = 'Subcategory_Image_';

    const VERIFIED = 1;
    const UNVERIFIED = 0;

    //Clients
    const CLIENT_PENDING = 'pending';
    const CLIENT_VERIFIED = 'verified';
    const CLIENT_ALL = 'all';
    const CLIENT_PREPAID = 'PREPAID';
    const CLIENT_POSTPAID = 'POSTPAID';

    //Service Requests
    const SERVICE_REQUEST_PENDING = 'pending';
    const SERVICE_REQUEST_ONGOING = 'ongoing';
    const SERVICE_REQUEST_COMPLETED = 'completed';
    const SERVICE_REQUEST_SUSPENDED = 'suspended';
    const SERVICE_REQUEST_CANCELLED = 'cancelled';

    //Service Request Status
    const SERVICE_REQUEST_STATUS_PENDING = 'PENDING';
    const SERVICE_REQUEST_STATUS_WORKER_ASSIGNED = 'WORKER_ASSIGNED';
    const SERVICE_REQUEST_STATUS_WORKER_COMMENCED = 'WORKER_COMMENCED';
    const SERVICE_REQUEST_STATUS_WORKER_COMPLETED = 'WORKER_COMPLETED';
    const SERVICE_REQUEST_STATUS_WORKER_SUSPENDED = 'WORKER_SUSPENDED';
    const SERVICE_REQUEST_STATUS_WORKER_CANCELLED = 'WORKER_CANCELLED';
    const SERVICE_REQUEST_STATUS_USER_COMPLETED = 'USER_COMPLETED';
    const SERVICE_REQUEST_STATUS_USER_COMPLAINT = 'USER_COMPLAINT';
    const SERVICE_REQUEST_STATUS_USER_CANCELLED = 'USER_CANCELLED';
    const SERVICE_REQUEST_STATUS_INVOICE_REQUESTED = 'INVOICE_REQUESTED';
    const SERVICE_REQUEST_STATUS_INVOICE_CREATED = 'INVOICE_CREATED';
    const SERVICE_REQUEST_STATUS_INVOICE_PAID = 'INVOICE_PAID';
    const SERVICE_REQUEST_STATUS_INVOICE_REJECTED = 'INVOICE_REJECTED';
    const SERVICE_REQUEST_STATUS_INVOICE_REQEUEST_REJECTED = 'INVOICE_REQUEST_REJECTED';
    


    //Invoice Requests
    const INVOICE_REQUEST_PENDING = 'pending';
    const INVOICE_REQUEST_CONFIMED = 'confirmed';
    const INVOICE_REQUEST_REJECTED = 'rejected';

      //Service Request Status
    const INVOICE_REQUEST_STATUS_PENDING = 'PENDING';
    const INVOICE_REQUEST_STATUS_CONFIRMED = 'CONFIRMED';
    const INVOICE_REQUEST_STATUS_REJECTED = 'REJECTED';

    //Invoices Status
    const INVOICE_STATUS_NEW = 'NEW';
    const INVOICE_STATUS_PENDING = 'PENDING';
    const INVOICE_STATUS_REJECTED = 'REJECTED';
    const INVOICE_STATUS_ACCEPTED = 'ACCEPTED';
    const INVOICE_PAID = 'paid';
    const INVOICE_PENDING = 'pending';
    const INVOICE_REJECTED = 'rejected';
    const INVOICE_NEW = 'new';

    //Complaints
    const COMPLAINTS_UNRESOLVED = 'unresolved';
    const COMPLAINTS_RESOLVED = 'resolved';
    const COMPLAINTS_STATUS_NEW = 'PENDING';
    const COMPLAINTS_STATUS_OPENED = 'OPENED';
    const COMPLAINTS_STATUS_CLOSED = 'CLOSED';

    const INVOICE_SERVICE_REQUEST_TYPE_PREMIUM = 'PREMIUM';
    const INVOICE_SERVICE_REQUEST_TYPE_FLEX = 'FLEX';

    const PUSH_NOTIFICATION_TYPE_ACCOUNT_TYPE = "ACCOUNT_TYPE";
    const PUSH_NOTIFICATION_TYPE_WORKER_VERIFIED = "WORKER_VERIFICATION";
    const PUSH_NOTIFICATION_TYPE_SERVICE_REQUEST = "SERVICE_REQUEST";
    const PUSH_NOTIFICATION_TYPE_WORKER_VERIFICATION = "WORKER_VERIFICATION";
    const PUSH_NOTIFICATION_TYPE_INVOICE = "INVOICE";
    const PUSH_NOTIFICATION_TYPE_USER_TYPE_CHANGE = "USER_TYPE_CHANGE";
    const PUSH_NOTIFICATION_TYPE_INVOICE_REQUEST_REJECTED = "INVOICE_REQUEST_REJECTED";
    const PUSH_NOTIFICATION_TYPE_COMPLAINT_CHAT = "COMPLAINT_CHAT";
    const PUSH_NOTIFICATION_TYPE_COMPLAINT = "COMPLAINT";

}
